# Generated by Django 3.1.2 on 2020-12-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visitor',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
