# Generated by Django 3.1.2 on 2020-12-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_url_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='visitor',
            field=models.IntegerField(default=0),
        ),
    ]
